/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\longwei\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-e5ab7270",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e5ab7270").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-c7dcfc8e",
    path: "/css/Css/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c7dcfc8e").then(next)
    },
  },
  {
    name: "v-301018ce",
    path: "/css/Css/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-301018ce").then(next)
    },
  },
  {
    name: "v-2253204d",
    path: "/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2253204d").then(next)
    },
  },
  {
    path: "/css/index.html",
    redirect: "/css/"
  },
  {
    name: "v-26c8059a",
    path: "/html/Html/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26c8059a").then(next)
    },
  },
  {
    name: "v-728122d3",
    path: "/html/Html/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-728122d3").then(next)
    },
  },
  {
    name: "v-a83da016",
    path: "/html/Interview/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a83da016").then(next)
    },
  },
  {
    name: "v-a37a979a",
    path: "/html/Interview/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a37a979a").then(next)
    },
  },
  {
    name: "v-5c8131ea",
    path: "/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c8131ea").then(next)
    },
  },
  {
    path: "/html/index.html",
    redirect: "/html/"
  },
  {
    name: "v-543a40b3",
    path: "/js%20-%20%E5%89%AF%E6%9C%AC/ES6/ES61.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-543a40b3").then(next)
    },
  },
  {
    path: "/js - 副本/ES6/ES61.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/ES6/ES61.html"
  },
  {
    path: "/js - 副本/ES6/ES61.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/ES6/ES61.html"
  },
  {
    name: "v-0f66a6f1",
    path: "/js%20-%20%E5%89%AF%E6%9C%AC/ES6/ES62.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f66a6f1").then(next)
    },
  },
  {
    path: "/js - 副本/ES6/ES62.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/ES6/ES62.html"
  },
  {
    path: "/js - 副本/ES6/ES62.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/ES6/ES62.html"
  },
  {
    name: "v-6b6c8cf3",
    path: "/js%20-%20%E5%89%AF%E6%9C%AC/Function/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b6c8cf3").then(next)
    },
  },
  {
    path: "/js - 副本/Function/text1.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/Function/text1.html"
  },
  {
    path: "/js - 副本/Function/text1.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/Function/text1.html"
  },
  {
    name: "v-ca0c001e",
    path: "/js%20-%20%E5%89%AF%E6%9C%AC/Function/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ca0c001e").then(next)
    },
  },
  {
    path: "/js - 副本/Function/text2.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/Function/text2.html"
  },
  {
    path: "/js - 副本/Function/text2.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/Function/text2.html"
  },
  {
    name: "v-5cd8d66b",
    path: "/js%20-%20%E5%89%AF%E6%9C%AC/JS/jsBase1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5cd8d66b").then(next)
    },
  },
  {
    path: "/js - 副本/JS/jsBase1.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/JS/jsBase1.html"
  },
  {
    path: "/js - 副本/JS/jsBase1.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/JS/jsBase1.html"
  },
  {
    name: "v-cf4f5e2e",
    path: "/js%20-%20%E5%89%AF%E6%9C%AC/JS/jsBase2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf4f5e2e").then(next)
    },
  },
  {
    path: "/js - 副本/JS/jsBase2.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/JS/jsBase2.html"
  },
  {
    path: "/js - 副本/JS/jsBase2.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/JS/jsBase2.html"
  },
  {
    name: "v-3bf37a87",
    path: "/js%20-%20%E5%89%AF%E6%9C%AC/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bf37a87").then(next)
    },
  },
  {
    path: "/js - 副本/",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/"
  },
  {
    path: "/js%20-%20%E5%89%AF%E6%9C%AC/index.html",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/"
  },
  {
    path: "/js - 副本/",
    redirect: "/js%20-%20%E5%89%AF%E6%9C%AC/"
  },
  {
    name: "v-3365566d",
    path: "/js/ES6/ES61.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3365566d").then(next)
    },
  },
  {
    name: "v-41b3248d",
    path: "/js/ES6/ES62.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41b3248d").then(next)
    },
  },
  {
    name: "v-31bc805a",
    path: "/js/Function/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31bc805a").then(next)
    },
  },
  {
    name: "v-2227a933",
    path: "/js/Function/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2227a933").then(next)
    },
  },
  {
    name: "v-379b7793",
    path: "/js/JS/jsBase1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-379b7793").then(next)
    },
  },
  {
    name: "v-f8fc2d1a",
    path: "/js/JS/jsBase2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f8fc2d1a").then(next)
    },
  },
  {
    name: "v-5d179fea",
    path: "/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d179fea").then(next)
    },
  },
  {
    path: "/js/index.html",
    redirect: "/js/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]