/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\longwei\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-e5ab7270",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e5ab7270").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-74033106",
    path: "/browser/Http/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74033106").then(next)
    },
  },
  {
    name: "v-3c39bed9",
    path: "/browser/Console/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c39bed9").then(next)
    },
  },
  {
    name: "v-7896620a",
    path: "/browser/Http/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7896620a").then(next)
    },
  },
  {
    name: "v-0133d579",
    path: "/browser/Console/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0133d579").then(next)
    },
  },
  {
    name: "v-0d209b79",
    path: "/browser/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d209b79").then(next)
    },
  },
  {
    name: "v-38255899",
    path: "/browser/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38255899").then(next)
    },
  },
  {
    name: "v-41963e03",
    path: "/browser/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41963e03").then(next)
    },
  },
  {
    path: "/browser/index.html",
    redirect: "/browser/"
  },
  {
    name: "v-36540fbd",
    path: "/browser/SourceCode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36540fbd").then(next)
    },
  },
  {
    name: "v-c7dcfc8e",
    path: "/css/Css/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c7dcfc8e").then(next)
    },
  },
  {
    name: "v-2253204d",
    path: "/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2253204d").then(next)
    },
  },
  {
    path: "/css/index.html",
    redirect: "/css/"
  },
  {
    name: "v-301018ce",
    path: "/css/Css/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-301018ce").then(next)
    },
  },
  {
    name: "v-26c8059a",
    path: "/html/Html/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26c8059a").then(next)
    },
  },
  {
    name: "v-a37a979a",
    path: "/html/Interview/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a37a979a").then(next)
    },
  },
  {
    name: "v-728122d3",
    path: "/html/Html/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-728122d3").then(next)
    },
  },
  {
    name: "v-a83da016",
    path: "/html/Interview/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a83da016").then(next)
    },
  },
  {
    name: "v-5c8131ea",
    path: "/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c8131ea").then(next)
    },
  },
  {
    path: "/html/index.html",
    redirect: "/html/"
  },
  {
    name: "v-3365566d",
    path: "/js/ES6/ES61.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3365566d").then(next)
    },
  },
  {
    name: "v-2227a933",
    path: "/js/Function/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2227a933").then(next)
    },
  },
  {
    name: "v-31bc805a",
    path: "/js/Function/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31bc805a").then(next)
    },
  },
  {
    name: "v-41b3248d",
    path: "/js/ES6/ES62.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41b3248d").then(next)
    },
  },
  {
    name: "v-379b7793",
    path: "/js/JS/jsBase1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-379b7793").then(next)
    },
  },
  {
    name: "v-f8fc2d1a",
    path: "/js/JS/jsBase2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f8fc2d1a").then(next)
    },
  },
  {
    name: "v-777e8bd6",
    path: "/ts%20copy/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-777e8bd6").then(next)
    },
  },
  {
    path: "/ts copy/Interview/1.html",
    redirect: "/ts%20copy/Interview/1.html"
  },
  {
    path: "/ts copy/Interview/1.html",
    redirect: "/ts%20copy/Interview/1.html"
  },
  {
    name: "v-e3c7a694",
    path: "/ts%20copy/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e3c7a694").then(next)
    },
  },
  {
    path: "/ts copy/Interview/2.html",
    redirect: "/ts%20copy/Interview/2.html"
  },
  {
    path: "/ts copy/Interview/2.html",
    redirect: "/ts%20copy/Interview/2.html"
  },
  {
    name: "v-5d179fea",
    path: "/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d179fea").then(next)
    },
  },
  {
    path: "/js/index.html",
    redirect: "/js/"
  },
  {
    name: "v-6ac76004",
    path: "/ts%20copy/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ac76004").then(next)
    },
  },
  {
    path: "/ts copy/",
    redirect: "/ts%20copy/"
  },
  {
    path: "/ts%20copy/index.html",
    redirect: "/ts%20copy/"
  },
  {
    path: "/ts copy/",
    redirect: "/ts%20copy/"
  },
  {
    name: "v-f215f6ec",
    path: "/ts%20copy/base/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f215f6ec").then(next)
    },
  },
  {
    path: "/ts copy/base/1.html",
    redirect: "/ts%20copy/base/1.html"
  },
  {
    path: "/ts copy/base/1.html",
    redirect: "/ts%20copy/base/1.html"
  },
  {
    name: "v-cc18779a",
    path: "/ts/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cc18779a").then(next)
    },
  },
  {
    name: "v-d0aba89e",
    path: "/ts/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d0aba89e").then(next)
    },
  },
  {
    name: "v-eaf99f70",
    path: "/ts%20copy/base/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eaf99f70").then(next)
    },
  },
  {
    path: "/ts copy/base/2.html",
    redirect: "/ts%20copy/base/2.html"
  },
  {
    path: "/ts copy/base/2.html",
    redirect: "/ts%20copy/base/2.html"
  },
  {
    name: "v-bdb1ff6a",
    path: "/ts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bdb1ff6a").then(next)
    },
  },
  {
    path: "/ts/index.html",
    redirect: "/ts/"
  },
  {
    name: "v-aec6c55a",
    path: "/ts/base/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aec6c55a").then(next)
    },
  },
  {
    name: "v-3bc1fece",
    path: "/vue/ES6/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bc1fece").then(next)
    },
  },
  {
    name: "v-9d038a0e",
    path: "/vue/ES6/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9d038a0e").then(next)
    },
  },
  {
    name: "v-77fbd7b3",
    path: "/ts/base/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77fbd7b3").then(next)
    },
  },
  {
    name: "v-340d0239",
    path: "/vue/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-340d0239").then(next)
    },
  },
  {
    name: "v-8c1bb04e",
    path: "/vue/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8c1bb04e").then(next)
    },
  },
  {
    name: "v-04892b47",
    path: "/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04892b47").then(next)
    },
  },
  {
    path: "/vue/index.html",
    redirect: "/vue/"
  },
  {
    name: "v-6e1c584e",
    path: "/vue/vue/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e1c584e").then(next)
    },
  },
  {
    name: "v-181434f9",
    path: "/vue/SourceCode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-181434f9").then(next)
    },
  },
  {
    name: "v-cf5de38e",
    path: "/vue/vue/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf5de38e").then(next)
    },
  },
  {
    name: "v-74d4a82f",
    path: "/vue/vue3/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74d4a82f").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]