/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\longwei\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-e5ab7270",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e5ab7270").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-0133d579",
    path: "/browser/Console/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0133d579").then(next)
    },
  },
  {
    name: "v-3c39bed9",
    path: "/browser/Console/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c39bed9").then(next)
    },
  },
  {
    name: "v-74033106",
    path: "/browser/Http/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74033106").then(next)
    },
  },
  {
    name: "v-7896620a",
    path: "/browser/Http/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7896620a").then(next)
    },
  },
  {
    name: "v-0d209b79",
    path: "/browser/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d209b79").then(next)
    },
  },
  {
    name: "v-38255899",
    path: "/browser/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38255899").then(next)
    },
  },
  {
    name: "v-41963e03",
    path: "/browser/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41963e03").then(next)
    },
  },
  {
    path: "/browser/index.html",
    redirect: "/browser/"
  },
  {
    name: "v-36540fbd",
    path: "/browser/SourceCode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36540fbd").then(next)
    },
  },
  {
    name: "v-366259ab",
    path: "/business/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-366259ab").then(next)
    },
  },
  {
    path: "/business/index.html",
    redirect: "/business/"
  },
  {
    name: "v-66231b5a",
    path: "/business/business/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66231b5a").then(next)
    },
  },
  {
    name: "v-6bdd528a",
    path: "/css/Css/1%20copy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bdd528a").then(next)
    },
  },
  {
    path: "/css/Css/1 copy.html",
    redirect: "/css/Css/1%20copy.html"
  },
  {
    path: "/css/Css/1 copy.html",
    redirect: "/css/Css/1%20copy.html"
  },
  {
    name: "v-1019a11a",
    path: "/business/business/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1019a11a").then(next)
    },
  },
  {
    name: "v-e5b49d4e",
    path: "/css/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e5b49d4e").then(next)
    },
  },
  {
    name: "v-100fe3f9",
    path: "/css/Css/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-100fe3f9").then(next)
    },
  },
  {
    name: "v-2253204d",
    path: "/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2253204d").then(next)
    },
  },
  {
    path: "/css/index.html",
    redirect: "/css/"
  },
  {
    name: "v-40b0a999",
    path: "/css/Css/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40b0a999").then(next)
    },
  },
  {
    name: "v-130ad6f9",
    path: "/css/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-130ad6f9").then(next)
    },
  },
  {
    name: "v-51abcbd3",
    path: "/html/Html/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51abcbd3").then(next)
    },
  },
  {
    name: "v-5ff999f3",
    path: "/html/Html/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ff999f3").then(next)
    },
  },
  {
    name: "v-a83da016",
    path: "/html/Interview/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a83da016").then(next)
    },
  },
  {
    name: "v-5c8131ea",
    path: "/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c8131ea").then(next)
    },
  },
  {
    path: "/html/index.html",
    redirect: "/html/"
  },
  {
    name: "v-a37a979a",
    path: "/html/Interview/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a37a979a").then(next)
    },
  },
  {
    name: "v-3365566d",
    path: "/js/ES6/ES61.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3365566d").then(next)
    },
  },
  {
    name: "v-41b3248d",
    path: "/js/ES6/ES62.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41b3248d").then(next)
    },
  },
  {
    name: "v-73b646da",
    path: "/js/JS/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73b646da").then(next)
    },
  },
  {
    name: "v-31bc805a",
    path: "/js/Function/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31bc805a").then(next)
    },
  },
  {
    name: "v-2227a933",
    path: "/js/Function/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2227a933").then(next)
    },
  },
  {
    name: "v-18839333",
    path: "/js/JS/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18839333").then(next)
    },
  },
  {
    name: "v-5d179fea",
    path: "/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d179fea").then(next)
    },
  },
  {
    path: "/js/index.html",
    redirect: "/js/"
  },
  {
    name: "v-236983a6",
    path: "/node/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-236983a6").then(next)
    },
  },
  {
    name: "v-1dc2a3eb",
    path: "/node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1dc2a3eb").then(next)
    },
  },
  {
    path: "/node/index.html",
    redirect: "/node/"
  },
  {
    name: "v-1c4d2c2a",
    path: "/node/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c4d2c2a").then(next)
    },
  },
  {
    name: "v-9540709a",
    path: "/node/base/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9540709a").then(next)
    },
  },
  {
    name: "v-78a4d45a",
    path: "/node/base/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78a4d45a").then(next)
    },
  },
  {
    name: "v-5254a65d",
    path: "/tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5254a65d").then(next)
    },
  },
  {
    path: "/tools/index.html",
    redirect: "/tools/"
  },
  {
    name: "v-e5766942",
    path: "/tools/vscode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e5766942").then(next)
    },
  },
  {
    name: "v-2e8b8e39",
    path: "/tools/git/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e8b8e39").then(next)
    },
  },
  {
    name: "v-ea099a46",
    path: "/tools/vscode/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ea099a46").then(next)
    },
  },
  {
    name: "v-cc18779a",
    path: "/ts/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cc18779a").then(next)
    },
  },
  {
    name: "v-d0aba89e",
    path: "/ts/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d0aba89e").then(next)
    },
  },
  {
    name: "v-aec6c55a",
    path: "/ts/base/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aec6c55a").then(next)
    },
  },
  {
    name: "v-bdb1ff6a",
    path: "/ts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bdb1ff6a").then(next)
    },
  },
  {
    path: "/ts/index.html",
    redirect: "/ts/"
  },
  {
    name: "v-77fbd7b3",
    path: "/ts/base/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77fbd7b3").then(next)
    },
  },
  {
    name: "v-3bc1fece",
    path: "/vue/ES6/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bc1fece").then(next)
    },
  },
  {
    name: "v-9d038a0e",
    path: "/vue/ES6/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9d038a0e").then(next)
    },
  },
  {
    name: "v-340d0239",
    path: "/vue/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-340d0239").then(next)
    },
  },
  {
    name: "v-8c1bb04e",
    path: "/vue/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8c1bb04e").then(next)
    },
  },
  {
    name: "v-04892b47",
    path: "/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04892b47").then(next)
    },
  },
  {
    path: "/vue/index.html",
    redirect: "/vue/"
  },
  {
    name: "v-181434f9",
    path: "/vue/SourceCode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-181434f9").then(next)
    },
  },
  {
    name: "v-6e1c584e",
    path: "/vue/vue/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e1c584e").then(next)
    },
  },
  {
    name: "v-74d4a82f",
    path: "/vue/vue3/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74d4a82f").then(next)
    },
  },
  {
    name: "v-cf5de38e",
    path: "/vue/vue/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf5de38e").then(next)
    },
  },
  {
    name: "v-92dde5b6",
    path: "/vue/vuex/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-92dde5b6").then(next)
    },
  },
  {
    name: "v-034a243b",
    path: "/vue/vuex/1copy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-034a243b").then(next)
    },
  },
  {
    name: "v-7a73bccb",
    path: "/vuePress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a73bccb").then(next)
    },
  },
  {
    path: "/vuePress/index.html",
    redirect: "/vuePress/"
  },
  {
    name: "v-c03087ba",
    path: "/vue/vuex/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c03087ba").then(next)
    },
  },
  {
    name: "v-0e660298",
    path: "/vuePress/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e660298").then(next)
    },
  },
  {
    name: "v-396fa49a",
    path: "/vuePress/pit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-396fa49a").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]