/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "资料库",
  "description": "Hello, my friend!",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-e5ab7270",
      "path": "/"
    },
    {
      "title": "jsbase 2",
      "frontmatter": {},
      "regularPath": "/browser/Http/1.html",
      "relativePath": "browser/Http/1.md",
      "key": "v-74033106",
      "path": "/browser/Http/1.html"
    },
    {
      "title": "ES62",
      "frontmatter": {},
      "regularPath": "/browser/Console/2.html",
      "relativePath": "browser/Console/2.md",
      "key": "v-3c39bed9",
      "path": "/browser/Console/2.html"
    },
    {
      "title": "jsbase 1",
      "frontmatter": {},
      "regularPath": "/browser/Http/2.html",
      "relativePath": "browser/Http/2.md",
      "key": "v-7896620a",
      "path": "/browser/Http/2.html"
    },
    {
      "title": "ES61",
      "frontmatter": {},
      "regularPath": "/browser/Console/1.html",
      "relativePath": "browser/Console/1.md",
      "key": "v-0133d579",
      "path": "/browser/Console/1.html"
    },
    {
      "title": "text1.md",
      "frontmatter": {},
      "regularPath": "/browser/Interview/1.html",
      "relativePath": "browser/Interview/1.md",
      "key": "v-0d209b79",
      "path": "/browser/Interview/1.html"
    },
    {
      "title": "text2.md",
      "frontmatter": {},
      "regularPath": "/browser/Interview/2.html",
      "relativePath": "browser/Interview/2.md",
      "key": "v-38255899",
      "path": "/browser/Interview/2.html"
    },
    {
      "title": "思维导图",
      "frontmatter": {},
      "regularPath": "/browser/",
      "relativePath": "browser/README.md",
      "key": "v-41963e03",
      "path": "/browser/"
    },
    {
      "title": "手写函数(简单)",
      "frontmatter": {},
      "regularPath": "/browser/SourceCode/1.html",
      "relativePath": "browser/SourceCode/1.md",
      "key": "v-36540fbd",
      "path": "/browser/SourceCode/1.html"
    },
    {
      "title": "text1.md",
      "frontmatter": {},
      "regularPath": "/css/Css/text1.html",
      "relativePath": "css/Css/text1.md",
      "key": "v-c7dcfc8e",
      "path": "/css/Css/text1.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-2253204d",
      "path": "/css/"
    },
    {
      "title": "text2.md",
      "frontmatter": {},
      "regularPath": "/css/Css/text2.html",
      "relativePath": "css/Css/text2.md",
      "key": "v-301018ce",
      "path": "/css/Css/text2.html"
    },
    {
      "title": "text1.md",
      "frontmatter": {},
      "regularPath": "/html/Html/text1.html",
      "relativePath": "html/Html/text1.md",
      "key": "v-26c8059a",
      "path": "/html/Html/text1.html"
    },
    {
      "title": "text2.md",
      "frontmatter": {},
      "regularPath": "/html/Interview/text2.html",
      "relativePath": "html/Interview/text2.md",
      "key": "v-a37a979a",
      "path": "/html/Interview/text2.html"
    },
    {
      "title": "text2.md",
      "frontmatter": {},
      "regularPath": "/html/Html/text2.html",
      "relativePath": "html/Html/text2.md",
      "key": "v-728122d3",
      "path": "/html/Html/text2.html"
    },
    {
      "title": "text1.md",
      "frontmatter": {},
      "regularPath": "/html/Interview/text1.html",
      "relativePath": "html/Interview/text1.md",
      "key": "v-a83da016",
      "path": "/html/Interview/text1.html"
    },
    {
      "title": "思维导图",
      "frontmatter": {},
      "regularPath": "/html/",
      "relativePath": "html/README.md",
      "key": "v-5c8131ea",
      "path": "/html/"
    },
    {
      "title": "ES61",
      "frontmatter": {},
      "regularPath": "/js/ES6/ES61.html",
      "relativePath": "js/ES6/ES61.md",
      "key": "v-3365566d",
      "path": "/js/ES6/ES61.html"
    },
    {
      "title": "手写函数(复杂)",
      "frontmatter": {},
      "regularPath": "/js/Function/text2.html",
      "relativePath": "js/Function/text2.md",
      "key": "v-2227a933",
      "path": "/js/Function/text2.html"
    },
    {
      "title": "手写函数(简单)",
      "frontmatter": {},
      "regularPath": "/js/Function/text1.html",
      "relativePath": "js/Function/text1.md",
      "key": "v-31bc805a",
      "path": "/js/Function/text1.html"
    },
    {
      "title": "ES62",
      "frontmatter": {},
      "regularPath": "/js/ES6/ES62.html",
      "relativePath": "js/ES6/ES62.md",
      "key": "v-41b3248d",
      "path": "/js/ES6/ES62.html"
    },
    {
      "title": "jsbase 2",
      "frontmatter": {},
      "regularPath": "/js/JS/jsBase1.html",
      "relativePath": "js/JS/jsBase1.md",
      "key": "v-379b7793",
      "path": "/js/JS/jsBase1.html"
    },
    {
      "title": "jsbase 1",
      "frontmatter": {},
      "regularPath": "/js/JS/jsBase2.html",
      "relativePath": "js/JS/jsBase2.md",
      "key": "v-f8fc2d1a",
      "path": "/js/JS/jsBase2.html"
    },
    {
      "title": "text1.md",
      "frontmatter": {},
      "regularPath": "/ts%20copy/Interview/1.html",
      "relativePath": "ts copy/Interview/1.md",
      "key": "v-777e8bd6",
      "path": "/ts%20copy/Interview/1.html"
    },
    {
      "title": "text2.md",
      "frontmatter": {},
      "regularPath": "/ts%20copy/Interview/2.html",
      "relativePath": "ts copy/Interview/2.md",
      "key": "v-e3c7a694",
      "path": "/ts%20copy/Interview/2.html"
    },
    {
      "title": "思维导图",
      "frontmatter": {},
      "regularPath": "/js/",
      "relativePath": "js/README.md",
      "key": "v-5d179fea",
      "path": "/js/"
    },
    {
      "title": "思维导图",
      "frontmatter": {},
      "regularPath": "/ts%20copy/",
      "relativePath": "ts copy/README.md",
      "key": "v-6ac76004",
      "path": "/ts%20copy/"
    },
    {
      "title": "jsbase 2",
      "frontmatter": {},
      "regularPath": "/ts%20copy/base/1.html",
      "relativePath": "ts copy/base/1.md",
      "key": "v-f215f6ec",
      "path": "/ts%20copy/base/1.html"
    },
    {
      "title": "text1.md",
      "frontmatter": {},
      "regularPath": "/ts/Interview/1.html",
      "relativePath": "ts/Interview/1.md",
      "key": "v-cc18779a",
      "path": "/ts/Interview/1.html"
    },
    {
      "title": "text2.md",
      "frontmatter": {},
      "regularPath": "/ts/Interview/2.html",
      "relativePath": "ts/Interview/2.md",
      "key": "v-d0aba89e",
      "path": "/ts/Interview/2.html"
    },
    {
      "title": "jsbase 1",
      "frontmatter": {},
      "regularPath": "/ts%20copy/base/2.html",
      "relativePath": "ts copy/base/2.md",
      "key": "v-eaf99f70",
      "path": "/ts%20copy/base/2.html"
    },
    {
      "title": "思维导图",
      "frontmatter": {},
      "regularPath": "/ts/",
      "relativePath": "ts/README.md",
      "key": "v-bdb1ff6a",
      "path": "/ts/"
    },
    {
      "title": "jsbase 2",
      "frontmatter": {},
      "regularPath": "/ts/base/1.html",
      "relativePath": "ts/base/1.md",
      "key": "v-aec6c55a",
      "path": "/ts/base/1.html"
    },
    {
      "title": "ES61",
      "frontmatter": {},
      "regularPath": "/vue/ES6/1.html",
      "relativePath": "vue/ES6/1.md",
      "key": "v-3bc1fece",
      "path": "/vue/ES6/1.html"
    },
    {
      "title": "ES62",
      "frontmatter": {},
      "regularPath": "/vue/ES6/2.html",
      "relativePath": "vue/ES6/2.md",
      "key": "v-9d038a0e",
      "path": "/vue/ES6/2.html"
    },
    {
      "title": "jsbase 1",
      "frontmatter": {},
      "regularPath": "/ts/base/2.html",
      "relativePath": "ts/base/2.md",
      "key": "v-77fbd7b3",
      "path": "/ts/base/2.html"
    },
    {
      "title": "text1.md",
      "frontmatter": {},
      "regularPath": "/vue/Interview/1.html",
      "relativePath": "vue/Interview/1.md",
      "key": "v-340d0239",
      "path": "/vue/Interview/1.html"
    },
    {
      "title": "text2.md",
      "frontmatter": {},
      "regularPath": "/vue/Interview/2.html",
      "relativePath": "vue/Interview/2.md",
      "key": "v-8c1bb04e",
      "path": "/vue/Interview/2.html"
    },
    {
      "title": "思维导图",
      "frontmatter": {},
      "regularPath": "/vue/",
      "relativePath": "vue/README.md",
      "key": "v-04892b47",
      "path": "/vue/"
    },
    {
      "title": "jsbase 2",
      "frontmatter": {},
      "regularPath": "/vue/vue/1.html",
      "relativePath": "vue/vue/1.md",
      "key": "v-6e1c584e",
      "path": "/vue/vue/1.html"
    },
    {
      "title": "手写函数(简单)",
      "frontmatter": {},
      "regularPath": "/vue/SourceCode/1.html",
      "relativePath": "vue/SourceCode/1.md",
      "key": "v-181434f9",
      "path": "/vue/SourceCode/1.html"
    },
    {
      "title": "jsbase 1",
      "frontmatter": {},
      "regularPath": "/vue/vue/2.html",
      "relativePath": "vue/vue/2.md",
      "key": "v-cf5de38e",
      "path": "/vue/vue/2.html"
    },
    {
      "title": "手写函数(简单)",
      "frontmatter": {},
      "regularPath": "/vue/vue3/1.html",
      "relativePath": "vue/vue3/1.md",
      "key": "v-74d4a82f",
      "path": "/vue/vue3/1.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "HTML",
        "link": "/html/"
      },
      {
        "text": "CSS",
        "link": "/css/"
      },
      {
        "text": "JS",
        "link": "/js/"
      }
    ],
    "sidebar": [
      {
        "path": "/html/",
        "title": "HTML",
        "children": [
          {
            "title": "html基础",
            "children": [
              {
                "path": "/html/Html/text1",
                "title": "html基础(1)"
              },
              {
                "path": "/html/Html/text2",
                "title": "html基础(2)"
              }
            ]
          },
          {
            "title": "面试",
            "children": [
              {
                "path": "/html/Interview/text1",
                "title": "简单"
              },
              {
                "path": "/html/Interview/text2",
                "title": "详细"
              }
            ]
          }
        ]
      },
      {
        "path": "/css/",
        "title": "CSS",
        "children": [
          {
            "title": "css基础",
            "children": [
              {
                "path": "/css/Css/text1",
                "title": "css基础(1)"
              },
              {
                "path": "/css/Css/text2",
                "title": "css基础(2)"
              }
            ]
          },
          {
            "title": "面试",
            "children": [
              {
                "path": "/css/Interview/text1",
                "title": "简单"
              },
              {
                "path": "/css/Interview/text2",
                "title": "详细"
              }
            ]
          }
        ]
      },
      {
        "path": "/js/",
        "title": "JS",
        "children": [
          {
            "title": "js基础",
            "children": [
              {
                "path": "/js/JS/jsBase1",
                "title": "js基础(1)"
              },
              {
                "path": "/js/JS/jsBase2",
                "title": "js基础(2)"
              }
            ]
          },
          {
            "title": "ES6",
            "children": [
              {
                "path": "/js/ES6/ES61",
                "title": "ES6(1)"
              },
              {
                "path": "/js/ES6/ES62",
                "title": "ES6(2)"
              }
            ]
          },
          {
            "title": "手写函数",
            "children": [
              {
                "path": "/js/Function/text1",
                "title": "手写函数(简单)"
              },
              {
                "path": "/js/Function/text2",
                "title": "手写函数(复杂)"
              }
            ]
          }
        ]
      },
      {
        "path": "/vue/",
        "title": "Vue",
        "children": [
          {
            "title": "vue基础",
            "children": [
              {
                "path": "/vue/vue/1",
                "title": "vue基础(1)"
              },
              {
                "path": "/vue/vue/2",
                "title": "vue基础(2)"
              }
            ]
          },
          {
            "title": "面试",
            "children": [
              {
                "path": "/vue/Interview/1",
                "title": "简单"
              },
              {
                "path": "/vue/Interview/2",
                "title": "详细"
              }
            ]
          },
          {
            "title": "源码分析",
            "children": [
              {
                "path": "/vue/SourceCode/1",
                "title": "源码分析(1)"
              }
            ]
          },
          {
            "title": "VUE3.0",
            "children": [
              {
                "path": "/vue/vue3/1",
                "title": "VUE3.0(1)"
              }
            ]
          }
        ]
      },
      {
        "path": "/browser/",
        "title": "浏览器",
        "children": [
          {
            "title": "Http",
            "children": [
              {
                "path": "/browser/Http/1",
                "title": "Http基础(1)"
              },
              {
                "path": "/browser/Http/2",
                "title": "Http基础(2)"
              }
            ]
          },
          {
            "title": "面试",
            "children": [
              {
                "path": "/browser/Interview/1",
                "title": "简单"
              },
              {
                "path": "/browser/Interview/2",
                "title": "详细"
              }
            ]
          },
          {
            "title": "浏览器调试",
            "children": [
              {
                "path": "/browser/Console/1",
                "title": "浏览器调试(1)"
              }
            ]
          }
        ]
      },
      {
        "path": "/ts/",
        "title": "TypeScript",
        "children": [
          {
            "title": "ts基础",
            "children": [
              {
                "path": "/ts/base/1",
                "title": "ts基础(1)"
              },
              {
                "path": "/ts/base/2",
                "title": "ts基础(2)"
              }
            ]
          },
          {
            "title": "面试",
            "children": [
              {
                "path": "/ts/Interview/1",
                "title": "简单"
              },
              {
                "path": "/ts/Interview/2",
                "title": "详细"
              }
            ]
          }
        ]
      },
      {
        "path": "/node/",
        "title": "Node",
        "children": [
          {
            "title": "node基础",
            "children": [
              {
                "path": "/node/base/1",
                "title": "node基础(1)"
              },
              {
                "path": "/node/base/2",
                "title": "node基础(2)"
              }
            ]
          },
          {
            "title": "面试",
            "children": [
              {
                "path": "/node/Interview/1",
                "title": "简单"
              },
              {
                "path": "/node/Interview/2",
                "title": "详细"
              }
            ]
          }
        ]
      }
    ],
    "sidebarDepth": 4
  }
}