/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "资料库",
  "description": "Hello, my friend!",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-e5ab7270",
      "path": "/"
    },
    {
      "title": "text1.md",
      "frontmatter": {},
      "regularPath": "/css/Css/text1.html",
      "relativePath": "css/Css/text1.md",
      "key": "v-c7dcfc8e",
      "path": "/css/Css/text1.html"
    },
    {
      "title": "text2.md",
      "frontmatter": {},
      "regularPath": "/css/Css/text2.html",
      "relativePath": "css/Css/text2.md",
      "key": "v-301018ce",
      "path": "/css/Css/text2.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-2253204d",
      "path": "/css/"
    },
    {
      "title": "text1.md",
      "frontmatter": {},
      "regularPath": "/html/Html/text1.html",
      "relativePath": "html/Html/text1.md",
      "key": "v-26c8059a",
      "path": "/html/Html/text1.html"
    },
    {
      "title": "text2.md",
      "frontmatter": {},
      "regularPath": "/html/Html/text2.html",
      "relativePath": "html/Html/text2.md",
      "key": "v-728122d3",
      "path": "/html/Html/text2.html"
    },
    {
      "title": "text1.md",
      "frontmatter": {},
      "regularPath": "/html/Interview/text1.html",
      "relativePath": "html/Interview/text1.md",
      "key": "v-a83da016",
      "path": "/html/Interview/text1.html"
    },
    {
      "title": "text2.md",
      "frontmatter": {},
      "regularPath": "/html/Interview/text2.html",
      "relativePath": "html/Interview/text2.md",
      "key": "v-a37a979a",
      "path": "/html/Interview/text2.html"
    },
    {
      "title": "思维导图",
      "frontmatter": {},
      "regularPath": "/html/",
      "relativePath": "html/README.md",
      "key": "v-5c8131ea",
      "path": "/html/"
    },
    {
      "title": "ES61",
      "frontmatter": {},
      "regularPath": "/js%20-%20%E5%89%AF%E6%9C%AC/ES6/ES61.html",
      "relativePath": "js - 副本/ES6/ES61.md",
      "key": "v-543a40b3",
      "path": "/js%20-%20%E5%89%AF%E6%9C%AC/ES6/ES61.html"
    },
    {
      "title": "ES62",
      "frontmatter": {},
      "regularPath": "/js%20-%20%E5%89%AF%E6%9C%AC/ES6/ES62.html",
      "relativePath": "js - 副本/ES6/ES62.md",
      "key": "v-0f66a6f1",
      "path": "/js%20-%20%E5%89%AF%E6%9C%AC/ES6/ES62.html"
    },
    {
      "title": "手写函数(简单)",
      "frontmatter": {},
      "regularPath": "/js%20-%20%E5%89%AF%E6%9C%AC/Function/text1.html",
      "relativePath": "js - 副本/Function/text1.md",
      "key": "v-6b6c8cf3",
      "path": "/js%20-%20%E5%89%AF%E6%9C%AC/Function/text1.html"
    },
    {
      "title": "手写函数(复杂)",
      "frontmatter": {},
      "regularPath": "/js%20-%20%E5%89%AF%E6%9C%AC/Function/text2.html",
      "relativePath": "js - 副本/Function/text2.md",
      "key": "v-ca0c001e",
      "path": "/js%20-%20%E5%89%AF%E6%9C%AC/Function/text2.html"
    },
    {
      "title": "jsbase 2",
      "frontmatter": {},
      "regularPath": "/js%20-%20%E5%89%AF%E6%9C%AC/JS/jsBase1.html",
      "relativePath": "js - 副本/JS/jsBase1.md",
      "key": "v-5cd8d66b",
      "path": "/js%20-%20%E5%89%AF%E6%9C%AC/JS/jsBase1.html"
    },
    {
      "title": "jsbase 1",
      "frontmatter": {},
      "regularPath": "/js%20-%20%E5%89%AF%E6%9C%AC/JS/jsBase2.html",
      "relativePath": "js - 副本/JS/jsBase2.md",
      "key": "v-cf4f5e2e",
      "path": "/js%20-%20%E5%89%AF%E6%9C%AC/JS/jsBase2.html"
    },
    {
      "title": "思维导图",
      "frontmatter": {},
      "regularPath": "/js%20-%20%E5%89%AF%E6%9C%AC/",
      "relativePath": "js - 副本/README.md",
      "key": "v-3bf37a87",
      "path": "/js%20-%20%E5%89%AF%E6%9C%AC/"
    },
    {
      "title": "ES61",
      "frontmatter": {},
      "regularPath": "/js/ES6/ES61.html",
      "relativePath": "js/ES6/ES61.md",
      "key": "v-3365566d",
      "path": "/js/ES6/ES61.html"
    },
    {
      "title": "ES62",
      "frontmatter": {},
      "regularPath": "/js/ES6/ES62.html",
      "relativePath": "js/ES6/ES62.md",
      "key": "v-41b3248d",
      "path": "/js/ES6/ES62.html"
    },
    {
      "title": "手写函数(简单)",
      "frontmatter": {},
      "regularPath": "/js/Function/text1.html",
      "relativePath": "js/Function/text1.md",
      "key": "v-31bc805a",
      "path": "/js/Function/text1.html"
    },
    {
      "title": "手写函数(复杂)",
      "frontmatter": {},
      "regularPath": "/js/Function/text2.html",
      "relativePath": "js/Function/text2.md",
      "key": "v-2227a933",
      "path": "/js/Function/text2.html"
    },
    {
      "title": "jsbase 2",
      "frontmatter": {},
      "regularPath": "/js/JS/jsBase1.html",
      "relativePath": "js/JS/jsBase1.md",
      "key": "v-379b7793",
      "path": "/js/JS/jsBase1.html"
    },
    {
      "title": "jsbase 1",
      "frontmatter": {},
      "regularPath": "/js/JS/jsBase2.html",
      "relativePath": "js/JS/jsBase2.md",
      "key": "v-f8fc2d1a",
      "path": "/js/JS/jsBase2.html"
    },
    {
      "title": "思维导图",
      "frontmatter": {},
      "regularPath": "/js/",
      "relativePath": "js/README.md",
      "key": "v-5d179fea",
      "path": "/js/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "html",
        "link": "/html/"
      },
      {
        "text": "css",
        "link": "/css/"
      },
      {
        "text": "js",
        "link": "/js/"
      }
    ],
    "sidebar": [
      {
        "path": "/html/",
        "title": "HTML",
        "children": [
          {
            "title": "html基础",
            "children": [
              {
                "path": "/html/Html/text1",
                "title": "html基础(1)"
              },
              {
                "path": "/html/Html/text2",
                "title": "html基础(2)"
              }
            ]
          },
          {
            "title": "面试",
            "children": [
              {
                "path": "/html/Interview/text1",
                "title": "简单"
              },
              {
                "path": "/html/Interview/text2",
                "title": "详细"
              }
            ]
          }
        ]
      },
      {
        "path": "/css/",
        "title": "CSS",
        "children": [
          {
            "title": "css基础",
            "children": [
              {
                "path": "/css/Css/text1",
                "title": "css基础(1)"
              },
              {
                "path": "/css/Css/text2",
                "title": "css基础(2)"
              }
            ]
          },
          {
            "title": "面试",
            "children": [
              {
                "path": "/css/Interview/text1",
                "title": "简单"
              },
              {
                "path": "/css/Interview/text2",
                "title": "详细"
              }
            ]
          }
        ]
      },
      {
        "path": "/js/",
        "title": "JS",
        "children": [
          {
            "title": "js基础",
            "children": [
              {
                "path": "/js/JS/jsBase1",
                "title": "js基础(1)"
              },
              {
                "path": "/js/JS/jsBase2",
                "title": "js基础(2)"
              }
            ]
          },
          {
            "title": "ES6",
            "children": [
              {
                "path": "/js/ES6/ES61",
                "title": "ES6(1)"
              },
              {
                "path": "/js/ES6/ES62",
                "title": "ES6(2)"
              }
            ]
          },
          {
            "title": "手写函数",
            "children": [
              {
                "path": "/js/Function/text1",
                "title": "手写函数(简单)"
              },
              {
                "path": "/js/Function/text2",
                "title": "手写函数(复杂)"
              }
            ]
          }
        ]
      },
      {
        "path": "/js/",
        "title": "Vue",
        "children": [
          {
            "title": "js基础",
            "children": [
              {
                "path": "/js/JS/jsBase1",
                "title": "js基础(1)"
              },
              {
                "path": "/js/JS/jsBase2",
                "title": "js基础(2)"
              }
            ]
          },
          {
            "title": "ES6",
            "children": [
              {
                "path": "/js/ES6/ES61",
                "title": "ES6(1)"
              },
              {
                "path": "/js/ES6/ES62",
                "title": "ES6(2)"
              }
            ]
          },
          {
            "title": "手写函数",
            "children": [
              {
                "path": "/js/Function/text1",
                "title": "手写函数(简单)"
              },
              {
                "path": "/js/Function/text2",
                "title": "手写函数(复杂)"
              }
            ]
          }
        ]
      }
    ],
    "sidebarDepth": 4
  }
}